@startuml Codecouleur
left to right direction
skinparam actorStyle awesome
skinparam backgroundcolor Grey/Black
skinparam classBackgroundColor Wheat|CornflowerBlue
package Administration #White{
    actor Admin as ADMIN #Gold
    actor SuperAdmin as SUPADMIN #WhiteSmoke
}


Rectangle Quidideance #DarkCyan {
package Réceptionner #Green/MediumSeaGreen{
    ("Ouvrir mail") as BOX #White
    ("Ouvrir le lien pour changer de mot de passe") as OPE #White
}    


package Authentifier #Grey/DarkGrey {
    ("Se connecter") as CON #White
    ("Mot de passe oublié") as MOD #White
}
package Modifier #MediumPurple/Purple{
        ("Rediriger") as RED #White
    ("Changer mot de passe") as CHA #White
    ("Valider") as VAL #White
}




    SUPADMIN--|> ADMIN : Généralisation Super admin à admin



    ADMIN--up->CON #Gold

    MOD<--CON #Gold
    BOX<.-OPE #Gold : Include
    MOD-->BOX  #Gold : Envoie d'un email
    OPE-up-> CHA #Gold
    CHA-up-> VAL #Gold
    VAL-> RED #Gold

    
    
    



      
    
  
}

@enduml
