@startuml Connecter
autonumber
actor Admin #Black
Admin -> MDP.oublié : Afficher interface MDP oublié
activate MDP.oublié #SkyBlue
MDP.oublié --> Admin : Interface affichée
deactivate MDP.oublié
alt #GreenYellow Cas valdide 
MDP.oublié --> Admin : Envoie d'un lien par email
else #IndianRed Cas problème
MDP.oublié --> Admin : Erreur server redirection sur la page d'accueil
MDP.oublié --> Admin : Erreur d'adresse email retour mdp oublié
end


Admin -> Connexion : Afficher interface connexion
activate Connexion #SkyBlue
Connexion --> Admin : Interface affichée
loop #LightGrey Séquence connexion
Admin ->> Connexion : Saisir email
Admin ->> Connexion : Saisir mot de passe 
Admin -> Connexion : Cliquer sur Connexion
Connexion -[#Black]> Connexion : Contrôle de saisie
Connexion --> Admin : Afficher exception
end
deactivate Connexion
Connexion -> ConnexionValider : Succès de controle
deactivate ConnexionValider

ConnexionValider -> AdminV : Vérifier (email, mot de passe)
activate AdminV #SkyBlue
AdminV --> ConnexionValider : Reponse
deactivate AdminV
alt #IndianRed Cas problème
ConnexionValider --> Connexion : Voir alerte (Saisir votre email et votre mot de passe)
Connexion -> Admin : Message d'erreur affiché
else #GreenYellow Cas valide
ConnexionValider --> Connexion : Connexion validée
Connexion -> EspaceAccueil : Redirigé vers accueil
end 
deactivate Connexion

AdminV -> EspaceAccueil : Admin connecter
EspaceAccueil --> Admin : Redirection sur la page d'accueil du site
destroy Admin

@enduml